add ejahnGithub to codeowners-sigstore-js
sigstore/community pull request #280
Opened 2023-06-05 20:38 UTC by bdehamer

#### Summary
Add `ejahnGithub` as a maintainer on the `sigstore-js` project.

2023-06-05 21:58 UTC, trevrosen approved these changes

2023-06-05 22:01 UTC, trevrosen requested changes
https://github.com/sigstore/community/blob/ea332e8dc98e96a47b275fa007ac346a46bc87cf/github-sync/github-data/users.yaml#L178 <-- typo fix here (upper case the `g`) should fix this, so I don't think this is the right patch. 😄

2023-06-05 22:38 UTC, trevrosen commented
To be clear the previous lack of uppercase was definitely my bad. 😆

2023-06-06 13:08 UTC, trevrosen submitted a review, later dismissed

2023-06-06 17:18 UTC, bdehamer commented
@trevrosen let's try this . . . adding the correct username as a new entry. Will do the removal of the old name in a separate PR

2023-06-07 20:23 UTC, trevrosen approved these changes

2023-06-07 21:38 UTC, merged