Set workflow to use pull_request_target and add dependabot config
sigstore/community pull request #70
Opened 2022-07-21 13:08 UTC by cpanato

#### Summary
- Set workflow to use pull_request_target
this is needed to run the workflow for forks PRs (for example https://github.com/sigstore/community/pull/68) also to reduce any possible issue, i've set the action to be approved to all PRs is coming from non org members

- add dependabot config

#### Release Note

`n/a`

#### Documentation

`n/a`

2022-07-21 14:56 UTC, haydentherapper approved these changes
Thanks!

2022-07-21 23:57 UTC, haydentherapper commented
cc @bobcallaway

2022-07-22 11:17 UTC, bobcallaway reviewed
/hold

2022-07-22 16:44 UTC, haydentherapper requested changes
removing lgtm

2022-08-04 14:08 UTC, cpanato commented
closing in favor of https://github.com/sigstore/community/pull/83

2022-08-04 14:08 UTC, closed without merging